## ERRADO

In [ ]:
from google.colab import auth
auth.authenticate_user()

import gspread
from oauth2client.client import GoogleCredentials

gc = gspread.authorize(GoogleCredentials.get_application_default())

In [ ]:
worksheet = gc.open('Links quebrados do blog').sheet1
data = worksheet.get_all_values()

df = pd.DataFrame(data)
df

       0  ...            6
0      #  ...       Status
1      1  ...
2      2  ...  Funcionando
3      3  ...     Corrigir
4      4  ...
..   ...  ...          ...
409  409  ...
410  410  ...
411  411  ...
412  412  ...
413  413  ...

[414 rows x 7 columns]

## CERTO

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!ls '/content/drive/My Drive/Colab Notebooks'

 adicionar_linhas.ipynb  'Links quebrados do blog.xlsx'   sheets.ipynb
 bar_chart_race.ipynb	  lista.ipynb			  sopa_bonita.ipynb
 datas.ipynb		  MOZÃO.xlsx			  testes.ipynb
 linkedin		 'requests e re.ipynb'

In [ ]:
# from openpyxl import load_workbook as load
# from openpyxl import Workbook
import openpyxl

wb = openpyxl.load_workbook('/content/drive/My Drive/Colab Notebooks/Links quebrados do blog.xlsx')
ws = wb['Broken link checker']
first_column = ws["D"]

In [ ]:
first_column

(<Cell 'Broken link checker'.D1>,
 <Cell 'Broken link checker'.D2>,
 <Cell 'Broken link checker'.D3>,
 <Cell 'Broken link checker'.D4>,
 <Cell 'Broken link checker'.D5>,
 <Cell 'Broken link checker'.D6>,
 <Cell 'Broken link checker'.D7>,
 <Cell 'Broken link checker'.D8>,
 <Cell 'Broken link checker'.D9>,
 <Cell 'Broken link checker'.D10>,
 <Cell 'Broken link checker'.D11>,
 <Cell 'Broken link checker'.D12>,
 <Cell 'Broken link checker'.D13>,
 <Cell 'Broken link checker'.D14>,
 <Cell 'Broken link checker'.D15>,
 <Cell 'Broken link checker'.D16>,
 <Cell 'Broken link checker'.D17>,
 <Cell 'Broken link checker'.D18>,
 <Cell 'Broken link checker'.D19>,
 <Cell 'Broken link checker'.D20>,
 <Cell 'Broken link checker'.D21>,
 <Cell 'Broken link checker'.D22>,
 <Cell 'Broken link checker'.D23>,
 <Cell 'Broken link checker'.D24>,
 <Cell 'Broken link checker'.D25>,
 <Cell 'Broken link checker'.D26>,
 <Cell 'Broken link checker'.D27>,
 <Cell 'Broken link checker'.D28>,
 <Cell 'Broken link checker'.D29>,
 <Cell 'Broken link checker'.D30>,
 <Cell 'Broken link checker'.D31>,
 <Cell 'Broken link checker'.D32>,
 <Cell 'Broken link checker'.D33>,
 <Cell 'Broken link checker'.D34>,
 <Cell 'Broken link checker'.D35>,
 <Cell 'Broken link checker'.D36>,
 <Cell 'Broken link checker'.D37>,
 <Cell 'Broken link checker'.D38>,
 <Cell 'Broken link checker'.D39>,
 <Cell 'Broken link checker'.D40>,
 <Cell 'Broken link checker'.D41>,
 <Cell 'Broken link checker'.D42>,
 <Cell 'Broken link checker'.D43>,
 <Cell 'Broken link checker'.D44>,
 <Cell 'Broken link checker'.D45>,
 <Cell 'Broken link checker'.D46>,
 <Cell 'Broken link checker'.D47>,
 <Cell 'Broken link checker'.D48>,
 <Cell 'Broken link checker'.D49>,
 <Cell 'Broken link checker'.D50>,
 <Cell 'Broken link checker'.D51>,
 <Cell 'Broken link checker'.D52>,
 <Cell 'Broken link checker'.D53>,
 <Cell 'Broken link checker'.D54>,
 <Cell 'Broken link checker'.D55>,
 <Cell 'Broken link checker'.D56>,
 <Cell 'Broken link checker'.D57>,
 <Cell 'Broken link checker'.D58>,
 <Cell 'Broken link checker'.D59>,
 <Cell 'Broken link checker'.D60>,
 <Cell 'Broken link checker'.D61>,
 <Cell 'Broken link checker'.D62>,
 <Cell 'Broken link checker'.D63>,
 <Cell 'Broken link checker'.D64>,
 <Cell 'Broken link checker'.D65>,
 <Cell 'Broken link checker'.D66>,
 <Cell 'Broken link checker'.D67>,
 <Cell 'Broken link checker'.D68>,
 <Cell 'Broken link checker'.D69>,
 <Cell 'Broken link checker'.D70>,
 <Cell 'Broken link checker'.D71>,
 <Cell 'Broken link checker'.D72>,
 <Cell 'Broken link checker'.D73>,
 <Cell 'Broken link checker'.D74>,
 <Cell 'Broken link checker'.D75>,
 <Cell 'Broken link checker'.D76>,
 <Cell 'Broken link checker'.D77>,
 <Cell 'Broken link checker'.D78>,
 <Cell 'Broken link checker'.D79>,
 <Cell 'Broken link checker'.D80>,
 <Cell 'Broken link checker'.D81>,
 <Cell 'Broken link checker'.D82>,
 <Cell 'Broken link checker'.D83>,
 <Cell 'Broken link checker'.D84>,
 <Cell 'Broken link checker'.D85>,
 <Cell 'Broken link checker'.D86>,
 <Cell 'Broken link checker'.D87>,
 <Cell 'Broken link checker'.D88>,
 <Cell 'Broken link checker'.D89>,
 <Cell 'Broken link checker'.D90>,
 <Cell 'Broken link checker'.D91>,
 <Cell 'Broken link checker'.D92>,
 <Cell 'Broken link checker'.D93>,
 <Cell 'Broken link checker'.D94>,
 <Cell 'Broken link checker'.D95>,
 <Cell 'Broken link checker'.D96>,
 <Cell 'Broken link checker'.D97>,
 <Cell 'Broken link checker'.D98>,
 <Cell 'Broken link checker'.D99>,
 <Cell 'Broken link checker'.D100>,
 <Cell 'Broken link checker'.D101>,
 <Cell 'Broken link checker'.D102>,
 <Cell 'Broken link checker'.D103>,
 <Cell 'Broken link checker'.D104>,
 <Cell 'Broken link checker'.D105>,
 <Cell 'Broken link checker'.D106>,
 <Cell 'Broken link checker'.D107>,
 <Cell 'Broken link checker'.D108>,
 <Cell 'Broken link checker'.D109>,
 <Cell 'Broken link checker'.D110>,
 <Cell 'Broken link checker'.D111>,
 <Cell 'Broken link checker'.D112>,
 <Cell 'Broken link checker'.D113>,
 <Cell 'Broken link checker'.D114>,
 <Cell 'Broken link checker'.D115>,
 <Cell 'Broken link checker'.D116>,
 <Cell 'Broken link checker'.D117>,
 <Cell 'Broken link checker'.D118>,
 <Cell 'Broken link checker'.D119>,
 <Cell 'Broken link checker'.D120>,
 <Cell 'Broken link checker'.D121>,
 <Cell 'Broken link checker'.D122>,
 <Cell 'Broken link checker'.D123>,
 <Cell 'Broken link checker'.D124>,
 <Cell 'Broken link checker'.D125>,
 <Cell 'Broken link checker'.D126>,
 <Cell 'Broken link checker'.D127>,
 <Cell 'Broken link checker'.D128>,
 <Cell 'Broken link checker'.D129>,
 <Cell 'Broken link checker'.D130>,
 <Cell 'Broken link checker'.D131>,
 <Cell 'Broken link checker'.D132>,
 <Cell 'Broken link checker'.D133>,
 <Cell 'Broken link checker'.D134>,
 <Cell 'Broken link checker'.D135>,
 <Cell 'Broken link checker'.D136>,
 <Cell 'Broken link checker'.D137>,
 <Cell 'Broken link checker'.D138>,
 <Cell 'Broken link checker'.D139>,
 <Cell 'Broken link checker'.D140>,
 <Cell 'Broken link checker'.D141>,
 <Cell 'Broken link checker'.D142>,
 <Cell 'Broken link checker'.D143>,
 <Cell 'Broken link checker'.D144>,
 <Cell 'Broken link checker'.D145>,
 <Cell 'Broken link checker'.D146>,
 <Cell 'Broken link checker'.D147>,
 <Cell 'Broken link checker'.D148>,
 <Cell 'Broken link checker'.D149>,
 <Cell 'Broken link checker'.D150>,
 <Cell 'Broken link checker'.D151>,
 <Cell 'Broken link checker'.D152>,
 <Cell 'Broken link checker'.D153>,
 <Cell 'Broken link checker'.D154>,
 <Cell 'Broken link checker'.D155>,
 <Cell 'Broken link checker'.D156>,
 <Cell 'Broken link checker'.D157>,
 <Cell 'Broken link checker'.D158>,
 <Cell 'Broken link checker'.D159>,
 <Cell 'Broken link checker'.D160>,
 <Cell 'Broken link checker'.D161>,
 <Cell 'Broken link checker'.D162>,
 <Cell 'Broken link checker'.D163>,
 <Cell 'Broken link checker'.D164>,
 <Cell 'Broken link checker'.D165>,
 <Cell 'Broken link checker'.D166>,
 <Cell 'Broken link checker'.D167>,
 <Cell 'Broken link checker'.D168>,
 <Cell 'Broken link checker'.D169>,
 <Cell 'Broken link checker'.D170>,
 <Cell 'Broken link checker'.D171>,
 <Cell 'Broken link checker'.D172>,
 <Cell 'Broken link checker'.D173>,
 <Cell 'Broken link checker'.D174>,
 <Cell 'Broken link checker'.D175>,
 <Cell 'Broken link checker'.D176>,
 <Cell 'Broken link checker'.D177>,
 <Cell 'Broken link checker'.D178>,
 <Cell 'Broken link checker'.D179>,
 <Cell 'Broken link checker'.D180>,
 <Cell 'Broken link checker'.D181>,
 <Cell 'Broken link checker'.D182>,
 <Cell 'Broken link checker'.D183>,
 <Cell 'Broken link checker'.D184>,
 <Cell 'Broken link checker'.D185>,
 <Cell 'Broken link checker'.D186>,
 <Cell 'Broken link checker'.D187>,
 <Cell 'Broken link checker'.D188>,
 <Cell 'Broken link checker'.D189>,
 <Cell 'Broken link checker'.D190>,
 <Cell 'Broken link checker'.D191>,
 <Cell 'Broken link checker'.D192>,
 <Cell 'Broken link checker'.D193>,
 <Cell 'Broken link checker'.D194>,
 <Cell 'Broken link checker'.D195>,
 <Cell 'Broken link checker'.D196>,
 <Cell 'Broken link checker'.D197>,
 <Cell 'Broken link checker'.D198>,
 <Cell 'Broken link checker'.D199>,
 <Cell 'Broken link checker'.D200>,
 <Cell 'Broken link checker'.D201>,
 <Cell 'Broken link checker'.D202>,
 <Cell 'Broken link checker'.D203>,
 <Cell 'Broken link checker'.D204>,
 <Cell 'Broken link checker'.D205>,
 <Cell 'Broken link checker'.D206>,
 <Cell 'Broken link checker'.D207>,
 <Cell 'Broken link checker'.D208>,
 <Cell 'Broken link checker'.D209>,
 <Cell 'Broken link checker'.D210>,
 <Cell 'Broken link checker'.D211>,
 <Cell 'Broken link checker'.D212>,
 <Cell 'Broken link checker'.D213>,
 <Cell 'Broken link checker'.D214>,
 <Cell 'Broken link checker'.D215>,
 <Cell 'Broken link checker'.D216>,
 <Cell 'Broken link checker'.D217>,
 <Cell 'Broken link checker'.D218>,
 <Cell 'Broken link checker'.D219>,
 <Cell 'Broken link checker'.D220>,
 <Cell 'Broken link checker'.D221>,
 <Cell 'Broken link checker'.D222>,
 <Cell 'Broken link checker'.D223>,
 <Cell 'Broken link checker'.D224>,
 <Cell 'Broken link checker'.D225>,
 <Cell 'Broken link checker'.D226>,
 <Cell 'Broken link checker'.D227>,
 <Cell 'Broken link checker'.D228>,
 <Cell 'Broken link checker'.D229>,
 <Cell 'Broken link checker'.D230>,
 <Cell 'Broken link checker'.D231>,
 <Cell 'Broken link checker'.D232>,
 <Cell 'Broken link checker'.D233>,
 <Cell 'Broken link checker'.D234>,
 <Cell 'Broken link checker'.D235>,
 <Cell 'Broken link checker'.D236>,
 <Cell 'Broken link checker'.D237>,
 <Cell 'Broken link checker'.D238>,
 <Cell 'Broken link checker'.D239>,
 <Cell 'Broken link checker'.D240>,
 <Cell 'Broken link checker'.D241>,
 <Cell 'Broken link checker'.D242>,
 <Cell 'Broken link checker'.D243>,
 <Cell 'Broken link checker'.D244>,
 <Cell 'Broken link checker'.D245>,
 <Cell 'Broken link checker'.D246>,
 <Cell 'Broken link checker'.D247>,
 <Cell 'Broken link checker'.D248>,
 <Cell 'Broken link checker'.D249>,
 <Cell 'Broken link checker'.D250>,
 <Cell 'Broken link checker'.D251>,
 <Cell 'Broken link checker'.D252>,
 <Cell 'Broken link checker'.D253>,
 <Cell 'Broken link checker'.D254>,
 <Cell 'Broken link checker'.D255>,
 <Cell 'Broken link checker'.D256>,
 <Cell 'Broken link checker'.D257>,
 <Cell 'Broken link checker'.D258>,
 <Cell 'Broken link checker'.D259>,
 <Cell 'Broken link checker'.D260>,
 <Cell 'Broken link checker'.D261>,
 <Cell 'Broken link checker'.D262>,
 <Cell 'Broken link checker'.D263>,
 <Cell 'Broken link checker'.D264>,
 <Cell 'Broken link checker'.D265>,
 <Cell 'Broken link checker'.D266>,
 <Cell 'Broken link checker'.D267>,
 <Cell 'Broken link checker'.D268>,
 <Cell 'Broken link checker'.D269>,
 <Cell 'Broken link checker'.D270>,
 <Cell 'Broken link checker'.D271>,
 <Cell 'Broken link checker'.D272>,
 <Cell 'Broken link checker'.D273>,
 <Cell 'Broken link checker'.D274>,
 <Cell 'Broken link checker'.D275>,
 <Cell 'Broken link checker'.D276>,
 <Cell 'Broken link checker'.D277>,
 <Cell 'Broken link checker'.D278>,
 <Cell 'Broken link checker'.D279>,
 <Cell 'Broken link checker'.D280>,
 <Cell 'Broken link checker'.D281>,
 <Cell 'Broken link checker'.D282>,
 <Cell 'Broken link checker'.D283>,
 <Cell 'Broken link checker'.D284>,
 <Cell 'Broken link checker'.D285>,
 <Cell 'Broken link checker'.D286>,
 <Cell 'Broken link checker'.D287>,
 <Cell 'Broken link checker'.D288>,
 <Cell 'Broken link checker'.D289>,
 <Cell 'Broken link checker'.D290>,
 <Cell 'Broken link checker'.D291>,
 <Cell 'Broken link checker'.D292>,
 <Cell 'Broken link checker'.D293>,
 <Cell 'Broken link checker'.D294>,
 <Cell 'Broken link checker'.D295>,
 <Cell 'Broken link checker'.D296>,
 <Cell 'Broken link checker'.D297>,
 <Cell 'Broken link checker'.D298>,
 <Cell 'Broken link checker'.D299>,
 <Cell 'Broken link checker'.D300>,
 <Cell 'Broken link checker'.D301>,
 <Cell 'Broken link checker'.D302>,
 <Cell 'Broken link checker'.D303>,
 <Cell 'Broken link checker'.D304>,
 <Cell 'Broken link checker'.D305>,
 <Cell 'Broken link checker'.D306>,
 <Cell 'Broken link checker'.D307>,
 <Cell 'Broken link checker'.D308>,
 <Cell 'Broken link checker'.D309>,
 <Cell 'Broken link checker'.D310>,
 <Cell 'Broken link checker'.D311>,
 <Cell 'Broken link checker'.D312>,
 <Cell 'Broken link checker'.D313>,
 <Cell 'Broken link checker'.D314>,
 <Cell 'Broken link checker'.D315>,
 <Cell 'Broken link checker'.D316>,
 <Cell 'Broken link checker'.D317>,
 <Cell 'Broken link checker'.D318>,
 <Cell 'Broken link checker'.D319>,
 <Cell 'Broken link checker'.D320>,
 <Cell 'Broken link checker'.D321>,
 <Cell 'Broken link checker'.D322>,
 <Cell 'Broken link checker'.D323>,
 <Cell 'Broken link checker'.D324>,
 <Cell 'Broken link checker'.D325>,
 <Cell 'Broken link checker'.D326>,
 <Cell 'Broken link checker'.D327>,
 <Cell 'Broken link checker'.D328>,
 <Cell 'Broken link checker'.D329>,
 <Cell 'Broken link checker'.D330>,
 <Cell 'Broken link checker'.D331>,
 <Cell 'Broken link checker'.D332>,
 <Cell 'Broken link checker'.D333>,
 <Cell 'Broken link checker'.D334>,
 <Cell 'Broken link checker'.D335>,
 <Cell 'Broken link checker'.D336>,
 <Cell 'Broken link checker'.D337>,
 <Cell 'Broken link checker'.D338>,
 <Cell 'Broken link checker'.D339>,
 <Cell 'Broken link checker'.D340>,
 <Cell 'Broken link checker'.D341>,
 <Cell 'Broken link checker'.D342>,
 <Cell 'Broken link checker'.D343>,
 <Cell 'Broken link checker'.D344>,
 <Cell 'Broken link checker'.D345>,
 <Cell 'Broken link checker'.D346>,
 <Cell 'Broken link checker'.D347>,
 <Cell 'Broken link checker'.D348>,
 <Cell 'Broken link checker'.D349>,
 <Cell 'Broken link checker'.D350>,
 <Cell 'Broken link checker'.D351>,
 <Cell 'Broken link checker'.D352>,
 <Cell 'Broken link checker'.D353>,
 <Cell 'Broken link checker'.D354>,
 <Cell 'Broken link checker'.D355>,
 <Cell 'Broken link checker'.D356>,
 <Cell 'Broken link checker'.D357>,
 <Cell 'Broken link checker'.D358>,
 <Cell 'Broken link checker'.D359>,
 <Cell 'Broken link checker'.D360>,
 <Cell 'Broken link checker'.D361>,
 <Cell 'Broken link checker'.D362>,
 <Cell 'Broken link checker'.D363>,
 <Cell 'Broken link checker'.D364>,
 <Cell 'Broken link checker'.D365>,
 <Cell 'Broken link checker'.D366>,
 <Cell 'Broken link checker'.D367>,
 <Cell 'Broken link checker'.D368>,
 <Cell 'Broken link checker'.D369>,
 <Cell 'Broken link checker'.D370>,
 <Cell 'Broken link checker'.D371>,
 <Cell 'Broken link checker'.D372>,
 <Cell 'Broken link checker'.D373>,
 <Cell 'Broken link checker'.D374>,
 <Cell 'Broken link checker'.D375>,
 <Cell 'Broken link checker'.D376>,
 <Cell 'Broken link checker'.D377>,
 <Cell 'Broken link checker'.D378>,
 <Cell 'Broken link checker'.D379>,
 <Cell 'Broken link checker'.D380>,
 <Cell 'Broken link checker'.D381>,
 <Cell 'Broken link checker'.D382>,
 <Cell 'Broken link checker'.D383>,
 <Cell 'Broken link checker'.D384>,
 <Cell 'Broken link checker'.D385>,
 <Cell 'Broken link checker'.D386>,
 <Cell 'Broken link checker'.D387>,
 <Cell 'Broken link checker'.D388>,
 <Cell 'Broken link checker'.D389>,
 <Cell 'Broken link checker'.D390>,
 <Cell 'Broken link checker'.D391>,
 <Cell 'Broken link checker'.D392>,
 <Cell 'Broken link checker'.D393>,
 <Cell 'Broken link checker'.D394>,
 <Cell 'Broken link checker'.D395>,
 <Cell 'Broken link checker'.D396>,
 <Cell 'Broken link checker'.D397>,
 <Cell 'Broken link checker'.D398>,
 <Cell 'Broken link checker'.D399>,
 <Cell 'Broken link checker'.D400>,
 <Cell 'Broken link checker'.D401>,
 <Cell 'Broken link checker'.D402>,
 <Cell 'Broken link checker'.D403>,
 <Cell 'Broken link checker'.D404>,
 <Cell 'Broken link checker'.D405>,
 <Cell 'Broken link checker'.D406>,
 <Cell 'Broken link checker'.D407>,
 <Cell 'Broken link checker'.D408>,
 <Cell 'Broken link checker'.D409>,
 <Cell 'Broken link checker'.D410>,
 <Cell 'Broken link checker'.D411>,
 <Cell 'Broken link checker'.D412>,
 <Cell 'Broken link checker'.D413>,
 <Cell 'Broken link checker'.D414>)

In [ ]:
ws.cell(row=200, column=4).hyperlink.target

'https://blog.psicologiaviva.com.br/adaptacao-em-tempos-de-covid-19/'

In [ ]:
ws.max_row

414

In [ ]:
lista = []
for i in range(2, ws.max_row+1):
    lista.append(ws.cell(row=i, column=4).hyperlink.target)

In [ ]:
len(lista)

413

In [ ]:
lista

['https://blog.psicologiaviva.com.br/',
 'https://blog.psicologiaviva.com.br/author/contatopsicologiaviva-com-br/',
 'https://blog.psicologiaviva.com.br/entrando-em-depressao/',
 'https://blog.psicologiaviva.com.br/entrando-em-depressao/',
 'https://blog.psicologiaviva.com.br/sindrome-de-burnout/',
 'https://blog.psicologiaviva.com.br/inteligencia-emocional/',
 'https://blog.psicologiaviva.com.br/primeira-consulta-com-psicologo/',
 'https://blog.psicologiaviva.com.br/superar-a-depressao/',
 'https://blog.psicologiaviva.com.br/questionario-de-ansiedade-e-depressao-2/',
 'https://blog.psicologiaviva.com.br/entrando-em-depressao/',
 'https://blog.psicologiaviva.com.br/entrando-em-depressao/',
 'https://blog.psicologiaviva.com.br/entrando-em-depressao/',
 'https://blog.psicologiaviva.com.br/entrando-em-depressao/',
 'https://blog.psicologiaviva.com.br/entrando-em-depressao/',
 'https://blog.psicologiaviva.com.br/entrando-em-depressao/',
 'https://blog.psicologiaviva.com.br/entrando-em-depressao/',
 'https://blog.psicologiaviva.com.br/sindrome-de-burnout/',
 'https://blog.psicologiaviva.com.br/inteligencia-emocional/',
 'https://blog.psicologiaviva.com.br/atendimento-on-line/',
 'https://blog.psicologiaviva.com.br/atendimento-on-line/',
 'https://blog.psicologiaviva.com.br/primeira-consulta-com-psicologo/',
 'https://blog.psicologiaviva.com.br/primeira-consulta-com-psicologo/',
 'https://blog.psicologiaviva.com.br/superar-a-depressao/',
 'https://blog.psicologiaviva.com.br/procurar-um-psicologo/',
 'https://blog.psicologiaviva.com.br/sindrome-do-pensamento-acelerado/',
 'https://blog.psicologiaviva.com.br/o-que-faz-um-psicologo/',
 'https://blog.psicologiaviva.com.br/e-sindrome-de-burnout/',
 'https://blog.psicologiaviva.com.br/o-que-e-inteligencia-emocional/',
 'https://blog.psicologiaviva.com.br/trabalho-domina-a-sua-vida/',
 'https://blog.psicologiaviva.com.br/o-que-e-inteligencia-emocional/',
 'https://blog.psicologiaviva.com.br/startpsi/',
 'https://blog.psicologiaviva.com.br/psicologia-viva-e-destaque-no-evento-de-abertura-da-venture-builder-em-sp/',
 'https://blog.psicologiaviva.com.br/psicologia-viva-news-junho-2017/',
 'https://blog.psicologiaviva.com.br/o-estresse/',
 'https://blog.psicologiaviva.com.br/a-saude-emocional-no-trabalho/',
 'https://blog.psicologiaviva.com.br/ajudar-filho-na-escolha-profissional/',
 'https://blog.psicologiaviva.com.br/treino-encoberto/',
 'https://blog.psicologiaviva.com.br/treino-encoberto/',
 'https://blog.psicologiaviva.com.br/psicologia-viva-cria-coluna-de-e-sports/',
 'https://blog.psicologiaviva.com.br/psicologia-do-esporte/',
 'https://blog.psicologiaviva.com.br/autocuidado/',
 'https://blog.psicologiaviva.com.br/startpsi/',
 'https://blog.psicologiaviva.com.br/porto-seguro-saude/',
 'https://blog.psicologiaviva.com.br/prevenir-suicidio/',
 'https://blog.psicologiaviva.com.br/fevereiro-roxo/',
 'https://blog.psicologiaviva.com.br/educar-em-casa/',
 'https://blog.psicologiaviva.com.br/ansiedade-e-adolescencia/',
 'https://blog.psicologiaviva.com.br/controlar-a-ansiedade/',
 'https://blog.psicologiaviva.com.br/saude-home-office/',
 'https://blog.psicologiaviva.com.br/estresse-e-ansiedade/',
 'https://blog.psicologiaviva.com.br/dor-nao-superada/',
 'https://blog.psicologiaviva.com.br/a-autoconfianca/',
 'https://blog.psicologiaviva.com.br/sintomas-de-stress/',
 'https://blog.psicologiaviva.com.br/tristeza-e-depressao/',
 'https://blog.psicologiaviva.com.br/ciume-e-inveja/',
 'https://blog.psicologiaviva.com.br/sonhos-luto/',
 'https://blog.psicologiaviva.com.br/ciume-e-inveja/',
 'https://blog.psicologiaviva.com.br/e-depressao-ou-tristeza/',
 'https://blog.psicologiaviva.com.br/tag/inseguranca/',
 'https://blog.psicologiaviva.com.br/a-importancia-da-psicoterapia-para-o-estudante-de-psicologia/',
 'https://blog.psicologiaviva.com.br/cuida-da-sua-vida/',
 'https://blog.psicologiaviva.com.br/todos-estao-felizes/',
 'https://blog.psicologiaviva.com.br/inicio-de-ano-novo/',
 'https://blog.psicologiaviva.com.br/inicio-de-ano-novo/',
 'https://blog.psicologiaviva.com.br/insonia-causas/',
 'https://blog.psicologiaviva.com.br/o-que-e-depressao/',
 'https://blog.psicologiaviva.com.br/o-que-significa-autoestima/',
 'https://blog.psicologiaviva.com.br/fobia-social/',
 'https://blog.psicologiaviva.com.br/fobia-social/',
 'https://blog.psicologiaviva.com.br/autoconhecimento-e-desenvolvimento-pessoal/',
 'https://blog.psicologiaviva.com.br/autocuidado/',
 'https://blog.psicologiaviva.com.br/o-que-e-psicoterapia/',
 'https://blog.psicologiaviva.com.br/praticando-o-autoconhecimento/',
 'https://blog.psicologiaviva.com.br/amor-e-frustracao/',
 'https://blog.psicologiaviva.com.br/orgasmo-feminino/',
 'https://blog.psicologiaviva.com.br/depressao-infantil/',
 'https://blog.psicologiaviva.com.br/psicologo-paciente-bariatrico/',
 'https://blog.psicologiaviva.com.br/nomofobia-o-medo-intenso-de-ficar-sem-se-conectar/',
 'https://blog.psicologiaviva.com.br/podcast-empatia/',
 'https://blog.psicologiaviva.com.br/relacionamento-toxico/',
 'https://blog.psicologiaviva.com.br/estresse-no-telemarketing/',
 'https://blog.psicologiaviva.com.br/a-carencia/',
 'https://blog.psicologiaviva.com.br/uma-relacao-termina/',
 'https://blog.psicologiaviva.com.br/tag/transtornos-alimentares/',
 'https://blog.psicologiaviva.com.br/fevereiro-roxo/',
 'https://blog.psicologiaviva.com.br/ansiedade-e-adolescencia/',
 'https://blog.psicologiaviva.com.br/automutilacao-2/',
 'https://blog.psicologiaviva.com.br/automutilacao-2/',
 'https://blog.psicologiaviva.com.br/maturidade-emocional/',
 'https://blog.psicologiaviva.com.br/estresse-no-trabalho/',
 'https://blog.psicologiaviva.com.br/render-o-tempo/',
 'https://blog.psicologiaviva.com.br/inatividade-insatisfacao/',
 'https://blog.psicologiaviva.com.br/ansiedade-nao-desliga/',
 'https://blog.psicologiaviva.com.br/fobia-social-e-medo/',
 'https://blog.psicologiaviva.com.br/angustia/',
 'https://blog.psicologiaviva.com.br/tag/sindrome-do-panico/',
 'https://blog.psicologiaviva.com.br/ansiedade-na-mulher/',
 'https://blog.psicologiaviva.com.br/o-luto-e-o-natal/',
 'https://blog.psicologiaviva.com.br/resiliencia-na-escola/',
 'https://blog.psicologiaviva.com.br/reflexoes-sobre-a-pandemia/',
 'https://blog.psicologiaviva.com.br/reflexoes-sobre-a-pandemia/',
 'https://blog.psicologiaviva.com.br/reflexoes-sobre-a-pandemia/',
 'https://blog.psicologiaviva.com.br/ataque-de-panico/',
 'https://blog.psicologiaviva.com.br/ataque-de-panico/',
 'https://blog.psicologiaviva.com.br/o-medo-durante-a-pandemia/',
 'https://blog.psicologiaviva.com.br/ataque-de-panico/',
 'https://blog.psicologiaviva.com.br/o-mindfulness/',
 'https://blog.psicologiaviva.com.br/os-nossos-pensamento/',
 'https://blog.psicologiaviva.com.br/pandemia-luto/',
 'https://blog.psicologiaviva.com.br/ciume-e-inveja/',
 'https://blog.psicologiaviva.com.br/page/130/',
 'https://blog.psicologiaviva.com.br/ansiedade-coisas-que-voce-precisa-saber/',
 'https://blog.psicologiaviva.com.br/ansiedade-prejudica-o-rendimento-profissional/',
 'https://blog.psicologiaviva.com.br/medo-e-ansiedade/',
 'https://blog.psicologiaviva.com.br/entenda-o-que-a-terapia-cognitivo-comportamental-pode-fazer-por-voce/',
 'https://blog.psicologiaviva.com.br/ciume-nos-dias-de-hoje/',
 'https://blog.psicologiaviva.com.br/ciume-nos-dias-de-hoje/',
 'https://blog.psicologiaviva.com.br/transtorno-obsessivo-compulsivo/',
 'https://blog.psicologiaviva.com.br/suicidio-e-pandemia/',
 'https://blog.psicologiaviva.com.br/atividade-fisica-e-depressao/',
 'https://blog.psicologiaviva.com.br/depressao/',
 'https://blog.psicologiaviva.com.br/depressao/',
 'https://blog.psicologiaviva.com.br/depressao-profunda/',
 'https://blog.psicologiaviva.com.br/aconselhamento-psicologico/',
 'https://blog.psicologiaviva.com.br/aconselhamento-psicologico/',
 'https://blog.psicologiaviva.com.br/aconselhamento-psicologico/',
 'https://blog.psicologiaviva.com.br/aconselhamento-psicologico/',
 'https://blog.psicologiaviva.com.br/insonia-causas/',
 'https://blog.psicologiaviva.com.br/o-que-e-depressao/',
 'https://blog.psicologiaviva.com.br/o-que-e-depressao/',
 'https://blog.psicologiaviva.com.br/o-que-e-depressao/',
 'https://blog.psicologiaviva.com.br/fobia-social/',
 'https://blog.psicologiaviva.com.br/fobia-social/',
 'https://blog.psicologiaviva.com.br/depressao-infantil/',
 'https://blog.psicologiaviva.com.br/depressao-infantil/',
 'https://blog.psicologiaviva.com.br/depressao-infantil/',
 'https://blog.psicologiaviva.com.br/depressao-infantil/',
 'https://blog.psicologiaviva.com.br/tratar-sindrome-do-panico/',
 'https://blog.psicologiaviva.com.br/questionario-de-autoestima/',
 'https://blog.psicologiaviva.com.br/codependencia-emocional/',
 'https://blog.psicologiaviva.com.br/sindrome-do-panico-2/',
 'https://blog.psicologiaviva.com.br/motivacao/',
 'https://blog.psicologiaviva.com.br/meu-filho-e-inteligente/',
 'https://blog.psicologiaviva.com.br/seu-corpo/',
 'https://blog.psicologiaviva.com.br/empoderamento-e-liberdade/',
 'https://blog.psicologiaviva.com.br/esgotamento-profissional/',
 'https://blog.psicologiaviva.com.br/questoes-psiquiatricas/',
 'https://blog.psicologiaviva.com.br/baleia-azul/',
 'https://blog.psicologiaviva.com.br/como-manter-um-relacionamento-feliz/',
 'https://blog.psicologiaviva.com.br/depressao-tem-cura/',
 'https://blog.psicologiaviva.com.br/baleia-azul/',
 'https://blog.psicologiaviva.com.br/baleia-azul/',
 'https://blog.psicologiaviva.com.br/qualidade-de-vida/',
 'https://blog.psicologiaviva.com.br/tag/melhorar-a-autoestima/',
 'https://blog.psicologiaviva.com.br/automutilacao/',
 'https://blog.psicologiaviva.com.br/automutilacao/',
 'https://blog.psicologiaviva.com.br/um-relacionamento-abusivo/',
 'https://blog.psicologiaviva.com.br/luto/',
 'https://blog.psicologiaviva.com.br/luto/',
 'https://blog.psicologiaviva.com.br/psicoterapia-e-gravidez/',
 'https://blog.psicologiaviva.com.br/criar-um-perfil-arrasado/',
 'https://blog.psicologiaviva.com.br/saude-emocional/',
 'https://blog.psicologiaviva.com.br/saude-emocional/',
 'https://blog.psicologiaviva.com.br/coringa/',
 'https://blog.psicologiaviva.com.br/importancia-do-psicologo/',
 'https://blog.psicologiaviva.com.br/saude-emocional/',
 'https://blog.psicologiaviva.com.br/brincadeiras-perigosas/',
 'https://blog.psicologiaviva.com.br/dependencia-quimica/',
 'https://blog.psicologiaviva.com.br/gestao-de-conflito/',
 'https://blog.psicologiaviva.com.br/trabalho-do-psicologo/',
 'https://blog.psicologiaviva.com.br/consulta-psicologica-online/',
 'https://blog.psicologiaviva.com.br/consulta-psicologica-online/',
 'https://blog.psicologiaviva.com.br/consulta-psicologica-online/',
 'https://blog.psicologiaviva.com.br/doencas-psicologicas/',
 'https://blog.psicologiaviva.com.br/as-vezes-precisamos-de-poucos-minutos-para-conseguir-enxergar-solucoes-importantes-para-nossa-vida-3/',
 'https://blog.psicologiaviva.com.br/bem-estar/',
 'https://blog.psicologiaviva.com.br/dependencia-digital/',
 'https://blog.psicologiaviva.com.br/dependencia-digital/',
 'https://blog.psicologiaviva.com.br/tag/psicologo/',
 'https://blog.psicologiaviva.com.br/pessoa-com-depressao-profunda/',
 'https://blog.psicologiaviva.com.br/licenca-maternidade/',
 'https://blog.psicologiaviva.com.br/problemas-de-aprendizagem-nas-criancas/',
 'https://blog.psicologiaviva.com.br/relacionamento-abusivo/',
 'https://blog.psicologiaviva.com.br/licenca-maternidade/',
 'https://blog.psicologiaviva.com.br/crise-do-covid-19/',
 'https://blog.psicologiaviva.com.br/psicologo-psiquiatra-psicanalista/',
 'https://blog.psicologiaviva.com.br/a-autoestima/',
 'https://blog.psicologiaviva.com.br/tristeza-profunda/',
 'https://blog.psicologiaviva.com.br/controlando-a-ansiedade/',
 'https://blog.psicologiaviva.com.br/esgotamento-mental-e-trabalho/',
 'https://blog.psicologiaviva.com.br/medo-ansiedade-e-fobias/',
 'https://blog.psicologiaviva.com.br/positividade-no-sofrimento/',
 'https://blog.psicologiaviva.com.br/assertividade/',
 'https://blog.psicologiaviva.com.br/transtorno-do-estresse-pos-traumatico/',
 'https://blog.psicologiaviva.com.br/lideranca-e-gestao-de-pessoas/',
 'https://blog.psicologiaviva.com.br/lideranca-e-gestao-de-pessoas/',
 'https://blog.psicologiaviva.com.br/independencia-financeira/',
 'https://blog.psicologiaviva.com.br/retorno-ao-trabalho/',
 'https://blog.psicologiaviva.com.br/adaptacao-em-tempos-de-covid-19/',
 'https://blog.psicologiaviva.com.br/tag/posicionamento-de-mercado/',
 'https://blog.psicologiaviva.com.br/a-adocao-de-um-filho/',
 'https://blog.psicologiaviva.com.br/lidar-com-o-estresse/',
 'https://blog.psicologiaviva.com.br/estou-numa-crise-de-ansiedade/',
 'https://blog.psicologiaviva.com.br/quando-o-excesso-ou-o-tipo-de-trabalho-faz-adoecer/',
 'https://blog.psicologiaviva.com.br/seus-limites/',
 'https://blog.psicologiaviva.com.br/sua-autoestima-precisa/',
 'https://blog.psicologiaviva.com.br/qualidade-de-vida-trabalho/',
 'https://blog.psicologiaviva.com.br/qualidade-de-vida-trabalho/',
 'https://blog.psicologiaviva.com.br/orientacao-profissional/',
 'https://blog.psicologiaviva.com.br/orientacao-profissional/',
 'https://blog.psicologiaviva.com.br/orientacao-profissional/',
 'https://blog.psicologiaviva.com.br/orientacao-profissional/',
 'https://blog.psicologiaviva.com.br/orientacao-profissional/',
 'https://blog.psicologiaviva.com.br/o-que-e-psicoterapia-online/',
 'https://blog.psicologiaviva.com.br/aposentadoria/',
 'https://blog.psicologiaviva.com.br/programas-de-incentivos/',
 'https://blog.psicologiaviva.com.br/cerebro/',
 'https://blog.psicologiaviva.com.br/cerebro/',
 'https://blog.psicologiaviva.com.br/a-dor-de-existir/',
 'https://blog.psicologiaviva.com.br/falta-de-interesse-sexual-na-mulher/',
 'https://blog.psicologiaviva.com.br/autoconhecimento-e-depressao/',
 'https://blog.psicologiaviva.com.br/checar-as-redes-sociais/',
 'https://blog.psicologiaviva.com.br/checar-as-redes-sociais/',
 'https://blog.psicologiaviva.com.br/tag/bem-estar/',
 'https://blog.psicologiaviva.com.br/voce-sabe-se-comportar-nas-redes-sociais/',
 'https://blog.psicologiaviva.com.br/docencia/',
 'https://blog.psicologiaviva.com.br/ciclotimia/',
 'https://blog.psicologiaviva.com.br/lideranca-e-gestao-de-pessoas/',
 'https://blog.psicologiaviva.com.br/ciclotimia/',
 'https://blog.psicologiaviva.com.br/sentimento-de-culpa/',
 'https://blog.psicologiaviva.com.br/identificar-a-ansiedade/',
 'https://blog.psicologiaviva.com.br/como-se-conectar-consigo-mesmo/',
 'https://blog.psicologiaviva.com.br/saude-emocional-dos-filhos/',
 'https://blog.psicologiaviva.com.br/independencia-financeira/',
 'https://blog.psicologiaviva.com.br/psicoterapia-de-casal-e-seus-beneficios-para-o-relacionamento/',
 'https://blog.psicologiaviva.com.br/desemprego/',
 'https://blog.psicologiaviva.com.br/agressor-de-cyberbullying/',
 'https://blog.psicologiaviva.com.br/maes-de-quarentena/',
 'https://blog.psicologiaviva.com.br/angustia-e-suicidio/',
 'https://blog.psicologiaviva.com.br/ser-mae/',
 'https://blog.psicologiaviva.com.br/ser-mae/',
 'https://blog.psicologiaviva.com.br/ser-mae/',
 'https://blog.psicologiaviva.com.br/menino-nao-brinca-de-casinha/',
 'https://blog.psicologiaviva.com.br/nos-relacionamentos-amorosos/',
 'https://blog.psicologiaviva.com.br/os-conflitos-familiares/',
 'https://blog.psicologiaviva.com.br/a-comunicacao-nao-violenta/',
 'https://blog.psicologiaviva.com.br/vida-para-voce/',
 'https://blog.psicologiaviva.com.br/parto-pandemia/',
 'https://blog.psicologiaviva.com.br/validade-da-relacao/',
 'https://blog.psicologiaviva.com.br/entendendo-a-ansiedade/',
 'https://blog.psicologiaviva.com.br/transtorno-alimentar/',
 'https://blog.psicologiaviva.com.br/custo-beneficio/',
 'https://blog.psicologiaviva.com.br/magra/',
 'https://blog.psicologiaviva.com.br/burnout-na-area-de-enfermagem/',
 'https://blog.psicologiaviva.com.br/tag/abordagem-psicologica/',
 'https://blog.psicologiaviva.com.br/psicoterapia-corporal/',
 'https://blog.psicologiaviva.com.br/campanha-prevencao-suicidio/',
 'https://blog.psicologiaviva.com.br/saude-mental-no-ambiente-corporativo/',
 'https://blog.psicologiaviva.com.br/educar-os-filhos/',
 'https://blog.psicologiaviva.com.br/sobrecarga-de-trabalho-das-mulheres/',
 'https://blog.psicologiaviva.com.br/padroes-e-repeticoes/',
 'https://blog.psicologiaviva.com.br/discalculia/',
 'https://blog.psicologiaviva.com.br/tag/terapia/',
 'https://blog.psicologiaviva.com.br/depressao-adolescencia/',
 'https://blog.psicologiaviva.com.br/acontecer-mesmo/',
 'https://blog.psicologiaviva.com.br/passeando-pela-ansiedade/',
 'https://blog.psicologiaviva.com.br/pessoa-otimista-ou-pessimista/',
 'https://blog.psicologiaviva.com.br/sofrimento-psicologico-na-pandemia/',
 'https://blog.psicologiaviva.com.br/eu-sofro-com-ansiedade-generalizada/',
 'https://blog.psicologiaviva.com.br/equilibrio-emocional-covid-19/',
 'https://blog.psicologiaviva.com.br/ansiedade-e-medo/',
 'https://blog.psicologiaviva.com.br/ansiedade-controlar/',
 'https://blog.psicologiaviva.com.br/papeis-sociais/',
 'https://blog.psicologiaviva.com.br/questionario-ansiedade/',
 'https://blog.psicologiaviva.com.br/a-frustracao/',
 'https://blog.psicologiaviva.com.br/liberdade-e-escolhas/',
 'https://blog.psicologiaviva.com.br/amor-patologico/',
 'https://blog.psicologiaviva.com.br/dor/',
 'https://blog.psicologiaviva.com.br/tratamento-para-emagrecer/',
 'https://blog.psicologiaviva.com.br/luto-mais-saudavel/',
 'https://blog.psicologiaviva.com.br/atividades-escolares/',
 'https://blog.psicologiaviva.com.br/os-5-estagios-do-luto/',
 'https://blog.psicologiaviva.com.br/poliamor/',
 'https://blog.psicologiaviva.com.br/psicoterapia-positiva-e-pandemia/',
 'https://blog.psicologiaviva.com.br/sofrer-um-assalto/',
 'https://blog.psicologiaviva.com.br/psicanalista-dizer-aos-pacientes/',
 'https://blog.psicologiaviva.com.br/psicologia-e-emagrecimento/',
 'https://blog.psicologiaviva.com.br/dislexico/',
 'https://blog.psicologiaviva.com.br/dislexico/',
 'https://blog.psicologiaviva.com.br/ansiedade-generalizada-e-o-estresse/',
 'https://blog.psicologiaviva.com.br/tristeza-em-pandemia/',
 'https://blog.psicologiaviva.com.br/psicoterapia-e-tratamento-psiquiatrico/',
 'https://blog.psicologiaviva.com.br/nao-termino-o-que-comeco/',
 'https://blog.psicologiaviva.com.br/procrastinacao-no-trabalho/',
 'https://blog.psicologiaviva.com.br/o-habito-de-se-comparar/',
 'https://blog.psicologiaviva.com.br/evitar-os-conflitos-do-confinamento/',
 'https://blog.psicologiaviva.com.br/fobia-social-2/',
 'https://blog.psicologiaviva.com.br/autossabotagem/',
 'https://blog.psicologiaviva.com.br/ajudar-sem-se-sentir-sobrecarregada/',
 'https://blog.psicologiaviva.com.br/aprenda-a-conversar/',
 'https://blog.psicologiaviva.com.br/pre-natal-psicologico/',
 'https://blog.psicologiaviva.com.br/frustracao-infantil/',
 'https://blog.psicologiaviva.com.br/sindrome-ninho-vazio/',
 'https://blog.psicologiaviva.com.br/medo-de-aviao/',
 'https://blog.psicologiaviva.com.br/achar-que-esta-sempre-certo/',
 'https://blog.psicologiaviva.com.br/homossexualidade-pelo-lado-de-dentro/',
 'https://blog.psicologiaviva.com.br/fazer-terapia/',
 'https://blog.psicologiaviva.com.br/violencia-sexual-de-meninos-e-homens/',
 'https://blog.psicologiaviva.com.br/violencia-domestica-voce-sabe-como-procurar-ajuda/',
 'https://blog.psicologiaviva.com.br/ser-ou-postar/',
 'https://blog.psicologiaviva.com.br/transtorno-de-personalidade-limitrofe/',
 'https://blog.psicologiaviva.com.br/escolher-um-coach/',
 'https://blog.psicologiaviva.com.br/medo-de-sonhar/',
 'https://blog.psicologiaviva.com.br/ansiedade-definicao-e-sintomas/',
 'https://blog.psicologiaviva.com.br/seus-sonhos/',
 'https://blog.psicologiaviva.com.br/estou-formada-e-agora/',
 'https://blog.psicologiaviva.com.br/psicologia-organizacional/',
 'https://blog.psicologiaviva.com.br/depressao-pos-parto/',
 'https://blog.psicologiaviva.com.br/ansiedade-e-tudo-igual/',

In [ ]:
df = pd.DataFrame(lista)
df

                                                     0
0                  https://blog.psicologiaviva.com.br/
1    https://blog.psicologiaviva.com.br/author/cont...
2    https://blog.psicologiaviva.com.br/entrando-em...
3    https://blog.psicologiaviva.com.br/entrando-em...
4    https://blog.psicologiaviva.com.br/sindrome-de...
..                                                 ...
408  https://blog.psicologiaviva.com.br/alienacao-p...
409        https://blog.psicologiaviva.com.br/ser-mae/
410  https://blog.psicologiaviva.com.br/evitar-os-c...
411       https://blog.psicologiaviva.com.br/caso-toc/
412  https://blog.psicologiaviva.com.br/violencia-d...

[413 rows x 1 columns]

In [ ]:
df.to_excel('/content/drive/My Drive/Colab Notebooks/MOZÃO.xlsx')