In [ ]:
lista = ['abacaxi','banana']
tupla = ('abacaxi','banana')

In [ ]:
for i in lista:
    print(i)

abacaxi
banana

In [ ]:
for i in tupla:
    print(i)

abacaxi
banana

In [ ]:
import pandas as pd
from datetime import datetime
import numpy as np
from datetime import date
import re

In [ ]:
number = '100.00-'
re.sub(r"([0-9]+\.[0-9]+)(-)", r"\2\1", number)

'-100.00'

In [ ]:
re.match("([^0-9])", number)

In [ ]:
date.today()

datetime.date(2021, 9, 2)

In [ ]:
now = datetime.now().strftime(format='%Y-%m-%d %H:%m:%s')
type(now)

str

In [ ]:
type(datetime.now())

datetime.datetime

In [ ]:
datetime.utcnow

In [ ]:
pd.Timestamp(datetime.now())

Timestamp('2021-09-02 20:24:11.092448')

In [ ]:
lista = [[1,2,3],[1,4,5],[6,4,3]]
lista[0]

[1, 2, 3]

In [ ]:
df = pd.DataFrame(columns=["col1","col2","col3"])
df

Empty DataFrame
Columns: [col1, col2, col3]
Index: []

In [ ]:
a_series = pd.Series(lista[0], index=df.columns)
df = df.append(a_series, ignore_index=True)

a_series = pd.Series(lista[1], index=df.columns)
df = df.append(a_series, ignore_index=True)

a_series = pd.Series(lista[2], index=df.columns)
df = df.append(a_series, ignore_index=True)

df

  col1 col2 col3
0    1    2    3
1    1    4    5
2    6    4    3

In [ ]:
df['col1'].astype('str')

0    1
1    1
2    6
Name: col1, dtype: object

In [ ]:
df.loc[:,'col1']

0    1
1    1
2    6
Name: col1, dtype: object

In [ ]:
for i, row in df.iterrows():
    print(list(row))

[1, 2, 3]
[1, 4, 5]
[6, 4, 3]

In [ ]:
for i in range(df.shape[0]):
    print(df.loc[i,'col1'])

1
1
6

In [ ]:
df.loc[0,'col1']

1

In [ ]:
df = pd.DataFrame({'col1':[np.nan,2,3,4,5],
                'col2':[1,2,np.nan,4,5],
                'col3':[1,2,3,4,5],
                'col4':['1','2','3','4',np.nan]})

df.select_dtypes('object').fillna('-')

  col4
0    1
1    2
2    3
3    4
4    -

In [ ]:
df.select_dtypes('number').fillna(0)

   col1  col2  col3
0   0.0   1.0     1
1   2.0   2.0     2
2   3.0   0.0     3
3   4.0   4.0     4
4   5.0   5.0     5

In [ ]:
colunas = df.select_dtypes('number').columns
df[colunas] = df.select_dtypes('number').fillna(0)
df

   col1  col2  col3 col4
0   0.0   1.0     1    1
1   2.0   2.0     2    2
2   3.0   0.0     3    3
3   4.0   4.0     4    4
4   5.0   5.0     5  NaN

In [ ]:
col = ['col1','col4','col3','col2']
df[col]

   col1 col4  col3  col2
0   0.0    1     1   1.0
1   2.0    2     2   2.0
2   3.0    3     3   0.0
3   4.0    4     4   4.0
4   5.0  NaN     5   5.0

In [ ]:
df

   col1  col2  col3 col4
0   0.0   1.0     1    1
1   2.0   2.0     2    2
2   3.0   0.0     3    3
3   4.0   4.0     4    4
4   5.0   5.0     5  NaN

In [ ]:
df.select_dtypes('number').columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [ ]:
df

   col1  col2  col3 col4
0   0.0   1.0     1    1
1   2.0   2.0     2    2
2   3.0   0.0     3    3
3   4.0   4.0     4    4
4   5.0   5.0     5  NaN

In [ ]:
df['col1'].astype(str)

0    0.0
1    2.0
2    3.0
3    4.0
4    5.0
Name: col1, dtype: object

In [ ]:
df.dtypes

col1    float64
col2    float64
col3      int64
col4     object
dtype: object

In [ ]:
df['col1'].astype(int)

0    0
1    2
2    3
3    4
4    5
Name: col1, dtype: int64

In [ ]:
for index, row in df.iterrows():
    print(row['col1'])

0.0
2.0
3.0
4.0
5.0

In [ ]:
data = '20201012'

re.sub("([0-9]{4})([0-9]{2})([0-9]{2})", "\\1-\\2-\\3", data)

'2020-10-12'

In [ ]:
df1 = pd.DataFrame({'increment_id':[1,2,3,4,5,6], "valor1":[5,23,23,3,2,np.nan]})
df2 = pd.DataFrame({'entity_id':[1,2,3,4,5,6], "valor2":[45,231,54,342,32,np.nan]})
df3 = pd.DataFrame({'entity_id':[1,2,3,4,5,6], "valor3":['45','231','54','342','32','x']})

df2.merge(df3)

   entity_id  valor2 valor3
0          1    45.0     45
1          2   231.0    231
2          3    54.0     54
3          4   342.0    342
4          5    32.0     32
5          6     NaN      x

In [ ]:
df = df1.merge(df2, how='outer', left_on='increment_id', right_on='entity_id', suffixes=None)
df

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:7963: FutureWarning: Passing 'suffixes' as a <class 'NoneType'>, is not supported and may give unexpected results. Provide 'suffixes' as a tuple instead. In the future a 'TypeError' will be raised.
  validate=validate,

   increment_id  valor1  entity_id  valor2
0             1     5.0          1    45.0
1             2    23.0          2   231.0
2             3    23.0          3    54.0
3             4     3.0          4   342.0
4             5     2.0          5    32.0
5             6     NaN          6     NaN

In [ ]:
df.dtypes

increment_id      int64
valor1          float64
entity_id         int64
valor2          float64
dtype: object

In [ ]:
df['coluna'] = [1,2,3,np.nan,"",0]
df

   increment_id  valor1  entity_id  valor2 coluna
0             1     5.0          1    45.0      1
1             2    23.0          2   231.0      2
2             3    23.0          3    54.0      3
3             4     3.0          4   342.0    NaN
4             5     2.0          5    32.0
5             6     NaN          6     NaN      0

In [ ]:
df.shape

(6, 5)

In [ ]:
for i in range(5):
    print( i)

0
1
2
3
4

In [ ]:
for index, row in df.iterrows():
    print(list(row))

[1, 5.0, 1, 45.0, 1]
[2, 23.0, 2, 231.0, 2]
[3, 23.0, 3, 54.0, 3]
[4, 3.0, 4, 342.0, nan]
[5, 2.0, 5, 32.0, '']
[6, nan, 6, nan, 0]

In [ ]:
[1,2,3,2].index(2)

1

In [ ]:
lista = [1,4,6,23,6,32]

lista[2] = None

lista

[1, 4, None, 23, 6, 32]

In [ ]:
lista = [1,4,6,23,6,np.nan]

for i in range(len(lista)):
    if lista[i] is np.nan:
        lista[i] = None
lista

[1, 4, 6, 23, 6, None]

In [ ]:
df

   increment_id  valor1  entity_id  valor2 coluna
0             1     5.0          1    45.0      1
1             2    23.0          2   231.0      2
2             3    23.0          3    54.0      3
3             4     3.0          4   342.0    NaN
4             5     2.0          5    32.0
5             6     NaN          6     NaN      0

In [ ]:
df = df.fillna("VALOR_NULO")
df

   increment_id      valor1  entity_id      valor2      coluna
0             1           5          1          45           1
1             2          23          2         231           2
2             3          23          3          54           3
3             4           3          4         342  VALOR_NULO
4             5           2          5          32
5             6  VALOR_NULO          6  VALOR_NULO           0

In [ ]:
type(np.nan)

float

In [ ]:
for index, row in df.iterrows():
    print("-----------------")
    lista = list(row)
    print(lista)
    lista_nova = []
    for item in lista:
        if item == "VALOR_NULO":
            item = None
        lista_nova.append(item)
    print(lista_nova)

-----------------
[1, 5.0, 1, 45.0, 1]
[1, 5.0, 1, 45.0, 1]
-----------------
[2, 23.0, 2, 231.0, 2]
[2, 23.0, 2, 231.0, 2]
-----------------
[3, 23.0, 3, 54.0, 3]
[3, 23.0, 3, 54.0, 3]
-----------------
[4, 3.0, 4, 342.0, 'VALOR_NULO']
[4, 3.0, 4, 342.0, None]
-----------------
[5, 2.0, 5, 32.0, '']
[5, 2.0, 5, 32.0, '']
-----------------
[6, 'VALOR_NULO', 6, 'VALOR_NULO', 0]
[6, None, 6, None, 0]

In [ ]:
for index, row in df.iterrows():
    print("-----------------------------------")
    lista = list(row)
    for i in range(0,len(lista)-1):
        print(i)
        if lista[i] is np.nan:
            lista[i] = None
    print(lista)

-----------------------------------
[1, 5, 1, 45.0, 1]
0
1
2
3
[1, 5, 1, 45.0, 1]
-----------------------------------
[2, 23, 2, 231.0, 2]
0
1
2
3
[2, 23, 2, 231.0, 2]
-----------------------------------
[3, 23, 3, 54.0, 3]
0
1
2
3
[3, 23, 3, 54.0, 3]
-----------------------------------
[4, 3, 4, 342.0, nan]
0
1
2
3
[4, 3, 4, 342.0, nan]
-----------------------------------
[5, 2, 5, 32.0, '']
0
1
2
3
[5, 2, 5, 32.0, '']
-----------------------------------
[6, 99, 6, nan, 0]
0
1
2
3
[6, 99, 6, nan, 0]

In [ ]:
for index, row in df.iterrows():
    for celula in range(df.shape[1]):
        if row[celula] is np.nan:
            print("--------------")
            print(row[celula])
            row[celula] = None
            print(row)

--------------
nan
increment_id       4
valor1             3
entity_id          4
valor2           342
coluna          None
Name: 3, dtype: object

In [ ]:
df

   increment_id  valor1  entity_id  valor2 coluna
0             1       5          1      45      1
1             2      23          2     231      2
2             3      23          3      54      3
3             4       3          4     342    NaN
4             5       2          5      32
5             6      99          6       5      0

In [ ]:
df = pd.DataFrame({'a':['1.200',2,5,6]})

In [ ]:
[ re.sub('\.','',str(linha)) for linha in df['a'] ]

['1200', '2', '5', '6']

In [ ]:
df = pd.DataFrame({'x':['a','a','b','b'],'a':[200,20,54,62],'b':[74,25,500,63]})
df

   x    a    b
0  a  200   74
1  a   20   25
2  b   54  500
3  b   62   63

In [ ]:
df = df.groupby('x')['a'].sum().reset_index()
df

   x    a
0  a  220
1  b  116

In [ ]:
( 1 + 4 + 4 + 5 + 6 + 10 + 11 ) / 7

5.857142857142857

In [ ]:
x = ( 1 + 4 + 4 + 5)/4
(x + 6 + 10 + 11)/4

7.625

9.0

In [ ]:
#velho
df1 = pd.DataFrame({'data':['2021-01-15','2021-01-14','2021-01-13','2021-01-12'],"valor":[1,2,3,4]})

#novo
df2 = pd.DataFrame({'data':['2021-01-15','2021-01-16','2021-01-17','2021-01-18'],"valor":[1,2,3,4]})

In [ ]:
df1['data'] = pd.to_datetime(df1.data)
df2['data'] = pd.to_datetime(df2.data)

In [ ]:
df2

        data  valor
0 2021-01-15      1
1 2021-01-16      2
2 2021-01-17      3
3 2021-01-18      4

In [ ]:
maxima = df1.data.max()

In [ ]:
df2[df2.data > maxima]

        data  valor
1 2021-01-16      2
2 2021-01-17      3
3 2021-01-18      4

In [ ]:
pd.concat([df1,df2])

        data  valor
0 2021-01-15      1
1 2021-01-14      2
2 2021-01-13      3
3 2021-01-12      4
0 2021-01-15      1
1 2021-01-16      2
2 2021-01-17      3
3 2021-01-18      4

In [ ]:
df1

        data  valor
0 2021-01-15      1
1 2021-01-14      2
2 2021-01-13      3
3 2021-01-12      4

In [ ]:
df1.data.dt.strftime("%Y-%m-%d")

0    2021-01-15
1    2021-01-14
2    2021-01-13
3    2021-01-12
Name: data, dtype: object

In [ ]:
import numpy as np

In [ ]:
df = pd.DataFrame({'cep':['3111 - 0090','30410 - 2 03','30240 - 360'], 'dsd_or_ezd':["DSD",'DSD','EZD'], 'customer_number':[1,2,3], 'customer_internal_company_code':[100,200,300]})
df[['teste']] = df.cep.str.split(" - ", expand=True)[1]
df

            cep dsd_or_ezd  ...  customer_internal_company_code  teste
0   3111 - 0090        DSD  ...                             100   0090
1  30410 - 2 03        DSD  ...                             200   2 03
2   30240 - 360        EZD  ...                             300    360

[3 rows x 5 columns]

In [ ]:
#condition, value if condition is true, value if condition is false)
df['codigo_cliente'] = np.where(df['dsd_or_ezd'] == "DSD", df['customer_number'], df['customer_internal_company_code'])
df

  REGIONAL_TOTAL_DESC = Table.AddColumn(SEGMENTAÇÃO, "regional_total_descricao", 
each if [regional_descricao_] = "Rio de Janeiro" then "Sudeste" 

else if [regional_descricao_] = "Centro Oeste" then "Brasil 20" 

else if [regional_descricao_] = "Minas Gerais" then "Sudeste" 

else if [regional_descricao_] = "Nordeste" then "Brasil 20" 

else if [regional_descricao_] = "Rio Grande do Sul" then "Sul" 

else if [regional_descricao_] = "Norte" then "Brasil 20" 

else if [regional_descricao_] = "Santa Catarina" then "Sul" 

else if [regional_descricao_] = "Parana" then "Sul" 

else [regional_descricao_]),

In [ ]:
df = pd.DataFrame({'busn_operation_site_description':["Rio de Janeiro","Centro Oeste","Minas Gerais","Nordeste", "Rio Grande do Sul", 'Teste']})
df['regional_total_descricao'] = np.where(df['busn_operation_site_description']=="Rio de Janeiro", 'Sudeste', 
                                          np.where(df['busn_operation_site_description']=="Minas Gerais", 'Sudeste',
                                          np.where(df['busn_operation_site_description']=="Centro Oeste", "Brasil 20",
                                          np.where(df['busn_operation_site_description']=="Nordeste", "Brasil 20",
                                          np.where(df['busn_operation_site_description']=="Norte", 'Brasil 20',
                                          np.where(df['busn_operation_site_description']=="Rio Grande do Sul", 'Sul',
                                          np.where(df['busn_operation_site_description']=="Santa Catarina", 'Sul',
                                          np.where(df['busn_operation_site_description']=="Parana", 'Sul', 
                                                   df['busn_operation_site_description']))))))))
df

  busn_operation_site_description regional_total_descricao
0                  Rio de Janeiro                  Sudeste
1                    Centro Oeste                Brasil 20
2                    Minas Gerais                  Sudeste
3                        Nordeste                Brasil 20
4               Rio Grande do Sul                      Sul
5                           Teste                    Teste

In [ ]:
df = pd.DataFrame({'cpf':['8299527643','299527643']})
df['cpf'].str.zfill(11)

0    08299527643
1    00299527643
Name: cpf, dtype: object

In [ ]:
df = pd.DataFrame({'cep':['b','b','b', 'a','c'],'valor':['1','2','3','4','10']})
df

  cep valor
0   b     1
1   b     2
2   b     3
3   a     4
4   c    10

In [ ]:
df.valor.replace({"1":"1 - Segunda", "2":"2 - Terça", "3":"3 - Quarta","4":"4 - Quinta","5":"5 - Sexta","6":"6 - Sábado","7":"7 - Domingo"})

0    1 - Segunda
1      2 - Terça
2     3 - Quarta
3     4 - Quinta
4             10
Name: valor, dtype: object

In [ ]:
#"codigo_cliente", each if [dsd_ou_ezd] = "DSD" then [codigo_sap] else [codigo_cliente_ezd_])

In [ ]:
df['cep'] = df.cep.str.replace("a","c")
df

  cep  valor
0   b      1
1   b      2
2   b      3
3   c      4

In [ ]:
df['text_new'] = df['text'].str.split('::').str[0]

In [ ]:
df = pd.DataFrame({'valor1':['1,2','2,5','3','4,6','5','6'], "valor2":['5','2,3','2,3','3','2','nan'], "valor3":['5','2,3','2,3','3','2','nan'],
                   'teste':['a','b','c','c','c','d']})
df

  valor1 valor2 valor3 teste
0    1,2      5      5     a
1    2,5    2,3    2,3     b
2      3    2,3    2,3     c
3    4,6      3      3     c
4      5      2      2     c
5      6    nan    nan     d

In [ ]:
df['valor1'].str.replace(',','.')

0    1.2
1    2.5
2      3
3    4.6
4      5
5      6
Name: valor1, dtype: object

In [ ]:
df = pd.DataFrame({'valor1':['1,2','None','3','4,6','NaN','6'], "valor2":['5','2,3','2,3','3','2','nan'], "valor3":['5','2,3','2,3','3','2','nan'],
                   'teste':['a','b','c','c','c','d']})
df

  valor1 valor2 valor3 teste
0    1,2      5      5     a
1   None    2,3    2,3     b
2      3    2,3    2,3     c
3    4,6      3      3     c
4    NaN      2      2     c
5      6    nan    nan     d

In [ ]:
df = df.replace("None","")
df = df.replace("NaN","")
df = df.replace("nan","")
df = df.replace("None","")
df

  valor1 valor2 valor3 teste
0    1,2      5      5     a
1           2,3    2,3     b
2      3    2,3    2,3     c
3    4,6      3      3     c
4             2      2     c
5      6                   d

In [ ]:
df = pd.DataFrame({'valor1':['1,2','None','3',np.nan,np.nan,'6'], "valor2":['5',np.nan,'2,3','3','2',np.nan], "valor3":['5','2,3','2,3','3','2','nan'],
                   'teste':['a/nan/nan/nan','/nan/b/c/a','c/nan/nan/a','c/g/g/nan','c/h/a/g','d/h/fg/a']})
df

  valor1 valor2 valor3          teste
0    1,2      5      5  a/nan/nan/nan
1   None    NaN    2,3     /nan/b/c/a
2      3    2,3    2,3    c/nan/nan/a
3    NaN      3      3      c/g/g/nan
4    NaN      2      2        c/h/a/g
5      6    NaN    nan       d/h/fg/a

In [ ]:
df[['valor1','valor2']].fillna(0, inplace=True)
df

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,

  valor1 valor2 valor3          teste
0    1,2      5      5  a/nan/nan/nan
1   None    NaN    2,3     /nan/b/c/a
2      3    2,3    2,3    c/nan/nan/a
3    NaN      3      3      c/g/g/nan
4    NaN      2      2        c/h/a/g
5      6    NaN    nan       d/h/fg/a

In [ ]:
df.teste.str.replace("/nan", "")

0           a
1      /b/c/a
2         c/a
3       c/g/g
4     c/h/a/g
5    d/h/fg/a
Name: teste, dtype: object

In [ ]:
customer = pd.DataFrame({'dsd_or_ezd':['DSD','DSD','DSD','EZD','DSD'],
                        'customer_number':[1,1,1,1,1],
                        'customer_internal_company_code':['2','2','2','2','2']})
customer

  dsd_or_ezd  customer_number customer_internal_company_code
0        DSD                1                              2
1        DSD                1                              2
2        DSD                1                              2
3        EZD                1                              2
4        DSD                1                              2

In [ ]:
customer['codigo_cliente'] = np.where(customer['dsd_or_ezd'] == "DSD", customer['customer_number'],
                                      customer['customer_internal_company_code'])

customer

  dsd_or_ezd  customer_number customer_internal_company_code codigo_cliente
0        DSD                1                              2              1
1        DSD                1                              2              1
2        DSD                1                              2              1
3        EZD                1                              2              2
4        DSD                1                              2              1

In [ ]:
customer

  dsd_or_ezd  customer_number customer_internal_company_code codigo_cliente
0        DSD                1                              2              1
1        DSD                1                              2              1
2        DSD                1                              2              1
3        EZD                1                              2              2
4        DSD                1                              2              1

In [3]:
import re

In [2]:
lista = [("lng=-47.802664728268745, lat=-15.657013854445248"), 
         ("lng=-47.75042666463918, lat=-15.733476257312468"), 
         ("lng=-47.81892460800397, lat=-15.69134186360214"), 
         ("lng=-47.86033150700153, lat=-15.656099266599636"),
         ("lng=-47.807670409758806, lat=-15.653245748680474")]

In [17]:
lista_nova = []

for tupla in lista:
    longitude = re.findall("lng=(.*),", tupla)[0]
    latitude = re.findall("lat=(.*)", tupla)[0]
    lista_nova.append(longitude)
    lista_nova.append(latitude)

lista_nova

['-47.802664728268745',
 '-15.657013854445248',
 '-47.75042666463918',
 '-15.733476257312468',
 '-47.81892460800397',
 '-15.69134186360214',
 '-47.86033150700153',
 '-15.656099266599636',
 '-47.807670409758806',
 '-15.653245748680474']

In [1]:
from datetime import datetime

hour_now = datetime.today().strftime('%Y%m%d%H')

In [2]:
path = 's3://bucket/RECEIVED/pasta/file'

split_path = path.split('/')
bucket = split_path[2]
path = '/'.join(split_path[3:5])
file_prefix = split_path[-1]

f'{path}/{file_prefix}_{hour_now}'

'RECEIVED/pasta/file_2024032215'

In [3]:
'/'.join(split_path[3:-1])

'RECEIVED/pasta'